tree.py: Fix treeview_search_cb() argument mismatch
When trying to find a file in dirdiff or vcview mode the following
error would be displayed:
  TypeError: treeview_search_cb() takes exactly 5 arguments (6 given)

Add an unused "data" argument to treeview_search_cb() to silence the
warning and allow file searching to work.

Signed-off-by: Peter Tyser <ptyser@gmail.com>