Import emblem-new from Evolution
Emblems are considered deprecated since GNOME 3.32:
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/7f3f91f9c210ee240885c7d370c8ff3485c3a17b
and `emblem-new` has been removed in GNOME 42:
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/becf0674bb631bb2f2e092e1fb0f4d55cf380de7

This will cause Meld to complain loudly on vanilla GNOME, even breaking the file tree view:

	Traceback (most recent call last):
	  File "/nix/store/i9gy3x995nn7js4xipzw01gysq4fh5zz-meld-3.21.1/lib/python3.9/site-packages/meld/ui/emblemcellrenderer.py", line 100, in do_render
	    pixbuf = self._get_pixbuf(self.emblem_name, self._emblem_size)
	  File "/nix/store/i9gy3x995nn7js4xipzw01gysq4fh5zz-meld-3.21.1/lib/python3.9/site-packages/meld/ui/emblemcellrenderer.py", line 64, in _get_pixbuf
	    pixbuf = icon_theme.load_icon(name, size, 0).copy()
	gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'emblem-new' not present in theme Adwaita (0)

	cairo.Error: Context.restore() without matching Context.save()

`emblem-default-symbolic` and `emblem-symbolic-link` are still available.

Let’s bundle it with Meld as suggested.

Though, for improved contrast on GNOME 42’s blue folder icons,
let’s take the emblem from Evolution.

https://gitlab.gnome.org/GNOME/evolution/-/issues/1811#note_1423465