vc: Check for installed version control tools before use
Previously, meld blindly assumed that the proper version control software
was always installed.  This causes issues when the proper version control
software isn't installed.  For example, if 'bzr' is not installed,
running "meld ./" in a bzr repository would result in an error such as:

...
  File "/home/ptyser/meld_git/meld/meld/vc/_vc.py", line 194, in popen
    return subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE).stdout
  File "/usr/lib/python2.5/subprocess.py", line 594, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1147, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

This patch forces meld to check if the proper version control software is
installed before running any version control commands.

Signed-off-by: Peter Tyser <ptyser@gmail.com>